//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAproject.DB_connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type_import
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Procent { get; set; }
    
        public virtual Material_type_import_ID Material_type_import_ID { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
