//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAproject.DB_connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type_import_ID
    {
        public int ID { get; set; }
        public string Name_material { get; set; }
    
        public virtual Material_type_import Material_type_import { get; set; }
    }
}
