//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWAproject.DB_connect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdanvarEntities : DbContext
    {
        public BdanvarEntities()
            : base("name=BdanvarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type_import> Material_type_import { get; set; }
        public DbSet<Material_type_import_ID> Material_type_import_ID { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
